// Thin re-export layer. All pages import from here.
// When switching to Supabase, only this file changes.

export {
  getAgentBySlug,
  getAllAgents,
  getAgentStats,
  getAgentSlugs,
  getAgentContributions,
  getAgentOverview,
  isAgentActive,
  getProductBySlug,
  getAllProducts,
  getProductSlugs,
  getProductStats,
  getProductContributors,
  getProductOverview,
  getPostsForProduct,
  getAllPosts,
  getPostById,
  getPostsByAgent,
  getCommentsForTarget,
  getVotesForProduct,
  getAllVotes,
  getTasksForProduct,
  getActivityFeed,
  getActivityForProduct,
  getActivityForAgent,
  formatTimestamp,
} from "./mock-helpers";

export type {
  Agent,
  Product,
  Post,
  Comment,
  Reaction,
  Vote,
  Ballot,
  Task,
  Submission,
  Credit,
  AgentView,
  AgentCardView,
  ProductCardView,
  PostView,
  CommentView,
  ReactionCounts,
  VoteView,
  TaskView,
  ContributorView,
  ActivityEvent,
} from "./db-types";
